ARM: S3C2440: mini2440: Fix missing CONFIG_S3C_DEV_USB_HOST
Fix missing select of S3C_DEV_USB_HOST when building for mini2440
only. Fixes the following error:

built-in.o: undefined reference to `s3c_device_usb`

Signed-off-by: Ben Dooks <ben-linux@fluff.org>

[ mainline commit: 0bfb34f3a168ee598164803ab3147dd41fc3f843 ]

Signed-off-by: Thomas Gleixner <tglx@linutronix.de>