xfs: Add missing rw_semaphore annotation in ASSERT
fs/xfs/linux-2.6/xfs_super.c: In function ‘xfs_fs_clear_inode’:
fs/xfs/linux-2.6/xfs_super.c:1113: error: ‘struct rw_anon_semaphore’ has no member named ‘lock’
make[2]: *** [fs/xfs/linux-2.6/xfs_super.o] Error 1

Signed-off-by: Alessio Igor Bogani <abogani@texware.it>
LKML-Reference: <1266874422-3200-1-git-send-email-abogani@texware.it>
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>