Fix BPF selftests compilation error in bpf_iter.c (git-fixes)
Since SUSE commit 48da0c6e9010, BPF selftests fails to compile.

  .../tools/testing/selftests/bpf/prog_tests/bpf_iter.c: In function 'test_task_common_nocheck':
  .../tools/testing/selftests/bpf/prog_tests/bpf_iter.c:231:26: error: implicit declaration of function 'gettid'; did you mean 'getgid'? [-Werror=implicit-function-declaration]
      231 |         skel->bss->tid = gettid();
          |                          ^~~~~~
          |                          getgid

Fix the BPF selftests compilation failure by:
- bpf: handle implicit declaration of function gettid in
  bpf_iter.c
- Refresh
  patches.suse/selftests-bpf-Clean-up-open-coded-gettid-syscall-inv.patch.

suse-commit: 43aa3172aab3c42b3efb682c309505e82884dbc1